/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.status.showstatus;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int black=0x7f040007;
        /**  Default screen margins, per the Android Design guidelines. 
         */
        public static final int blue=0x7f040000;
        public static final int choose_eara_item_press_color=0x7f040008;
        public static final int d_grey=0x7f040003;
        public static final int grey=0x7f040002;
        public static final int l_lightgrey=0x7f040005;
        public static final int lightgrey=0x7f040004;
        public static final int no_color=0x7f04000a;
        public static final int popup_main_background=0x7f040006;
        public static final int red=0x7f040001;
        public static final int white=0x7f040009;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f050000;
        public static final int activity_vertical_margin=0x7f050001;
    }
    public static final class drawable {
        public static final int frame_grey=0x7f020000;
        public static final int frame_none=0x7f020001;
        public static final int ic_launcher=0x7f020002;
        public static final int makepublic_w=0x7f020003;
        public static final int more=0x7f020004;
        public static final int point100=0x7f020005;
        public static final int search1_s=0x7f020006;
        public static final int share=0x7f020007;
        public static final int share1=0x7f020008;
        public static final int untitled=0x7f020009;
        public static final int welcome=0x7f02000a;
    }
    public static final class id {
        public static final int log_logintextviewlinearlayout=0x7f08000f;
        public static final int log_personnameedittext=0x7f08000e;
        public static final int main_currentpersonname=0x7f080003;
        public static final int main_curtimetextview=0x7f080001;
        public static final int main_edittextview=0x7f08000c;
        public static final int main_moreoperaimageview=0x7f080002;
        public static final int main_moreoperalinearlayout=0x7f08000b;
        public static final int main_mystatustextview=0x7f080004;
        public static final int main_prompttextview=0x7f080006;
        public static final int main_researchpersonnumtextview=0x7f08000a;
        public static final int main_researchprompttextview=0x7f080009;
        public static final int main_samestatuspersonnum=0x7f080007;
        public static final int main_searchlinearlayout=0x7f080008;
        public static final int main_searchtextview=0x7f08000d;
        public static final int main_shareimageview=0x7f080000;
        public static final int main_statelinearlayout=0x7f080005;
        public static final int notificationImage=0x7f080010;
        public static final int notificationPercent=0x7f080012;
        public static final int notificationProgress=0x7f080013;
        public static final int notificationTitle=0x7f080011;
        public static final int stateedit_cancellinearlayout=0x7f080017;
        public static final int stateedit_prompttextview=0x7f080014;
        public static final int stateedit_sendlinearlayout=0x7f080016;
        public static final int stateedit_statusedittext=0x7f080015;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int log=0x7f030001;
        public static final int notification_item=0x7f030002;
        public static final int state_edit=0x7f030003;
    }
    public static final class string {
        public static final int action_settings=0x7f060002;
        public static final int app_name=0x7f060000;
        public static final int cancle=0x7f060006;
        public static final int hello_world=0x7f060001;
        public static final int search_state=0x7f060004;
        public static final int send_state=0x7f060003;
        public static final int sure=0x7f060005;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        
         */
        public static final int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f070001;
        public static final int Theme_AppStartLoad=0x7f070002;
    }
}
